'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const modules = ['policy', 'client', 'archive', 'install'];
let bundle = "'use strict';\n// Generated by scripts/build.cjs. Do not edit.\nconst factories = Object.create(null);\n";
for (const name of modules) {
  const source = fs.readFileSync(path.join(root, `src/${name}.cjs`), 'utf8').replaceAll('\r\n', '\n');
  bundle += `factories['./${name}.cjs'] = function(require, module, exports) {\n${source}\n};\n`;
}
bundle += `const cache = Object.create(null);
function load(id) {
  if (id.startsWith('node:')) return require(id);
  if (!Object.hasOwn(factories, id)) throw new Error('unknown module');
  if (!cache[id]) { const m = { exports: {} }; cache[id] = m; factories[id](load, m, m.exports); }
  return cache[id].exports;
}
module.exports = load('./install.cjs');
`;
for (const [file, contents] of [['bundle.cjs', bundle], ['index.cjs', fs.readFileSync(path.join(root, 'src/index.cjs'), 'utf8').replaceAll('\r\n', '\n')]]) {
  const destination = path.join(root, 'dist', file);
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(destination, 'utf8') !== contents) throw new Error('bundle differs from source');
  } else { fs.mkdirSync(path.dirname(destination), { recursive: true }); fs.writeFileSync(destination, contents); }
}
